name: FLAKS

on:
  pull_request:
 

jobs:

  hello-world:

    runs-on: ubuntu-latest

    steps:
    - name: checkoutcode
      uses: actions/checkout@v2

    -name: Set up Python
      uses: actions/setup-python@v2

    -name: Install dependencies
      run: pip install flask8

    -name: Fist Step

      run: flask8 code/python