name: FLAKS

on:
  pull_request:
 
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: build project
        container:
          image: ".code/python/Dockerfile"
          volumes:
            - .:/srv
        run: make test