name: unitest

on:
  push:
    branches:
      - "*"
 

jobs:

  hello-world:

    runs-on: ubuntu-latest

    steps:
    - name: checkoutcode
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Fist Step

      run: python -m unittest discover -s code/python -p "test_*.py"