name: unitest

on:
  push:
    branches:
      - "*"
 

jobs:

  hello-world:

    runs-on: ubuntu-latest

    steps:
    - name: checkoutcode
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      uses: pip install bandit

    - name: Fist Step

      run: bandit -r code/python